apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-web-thedisforduchesne
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-public-web-thedisforduchesne
  template:
    metadata:
      labels:
        app: flask-public-web-thedisforduchesne
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: thedisforduchesne-flask 
          image: hrichardson87/base-flask:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: public-web-thedisforduchesne-svc
spec:
  type: ClusterIP
  selector:
    app: flask-public-web-thedisforduchesne
  ports:
    - port: 5000
---
apiVersion: networking.k8s.io.v1
kind: Ingress
metadata:
  name: public-web-thedisforduchesne-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: thedisforduchesne.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: public-web-thedisforduchesne-svc
                port:
                  number: 5000
