---
apiVersion: v1
kind: Service
metadata:
  name: public-web-thedisforduchesne-svc
  namespace: thedisforduchesne
spec:
  type: ClusterIP
  selector:
    app: flask-public-web-thedisforduchesne
  ports:
    - port: 80
      targetPort: 5000
      name: svc-prt

